name: inboxzero
services:
  ui:
    build: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/app  
    networks:
      - inbox-zero-network
    env_file: .env
    # depends_on:
    #   api:
    #     condition: service_healthy
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/app  
    networks:
      - inbox-zero-network
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 10s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - inbox-zero-network
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - inbox-zero-network
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}

volumes:
  redis-data:
  postgres-data:

networks:
  inbox-zero-network:
    driver: bridge